---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '12'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf Scott Townsend}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center} stownsend678@gmail.com ∙ (562) 584-5017 ∙ \href{https://github.com/scotty369}{Github/GitLab: scotty369} ∙ \href{https://www.linkedin.com/in/scott-townsend-0ab515262/}{LinkedIn: Scott Townsend}
\end{center}
\vspace{10pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Brigham Young University}\end{flushleft}
    \begin{flushright}\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelors of Science: Data Science\end{flushleft}
    \begin{flushright}April 2022 - April 2025\end{flushright}
  \end{multicols}
  \begin{multicols}{2}
    \begin{flushleft}Minor: Statistics\end{flushleft}
  \end{multicols}
\end{large}

\vspace{0.05cm}

<!-- CERTIFICATIONS -->
\begin{large}{\bf CERTIFICATIONS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* Professional Data Engineer Certification (in progress) – Google Cloud

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}

* **Technical Tools & Languages:** Python, R, SQL, Power BI, Tableau, Metabase, Snowflake, Databricks, AWS, S3, Prefect, Docker, Git, HuggingFace, GitLab, GitHub

* **Microsoft Office Suite:** Proficient in Word, Excel, Outlook, and Access

* **Communication:** Strong verbal and written skills; able to convey complex information clearly

* **Collaboration & Leadership:** Effective team player with leadership orientation and initiative

* **Adaptability:** Quick learner with the ability to perform under pressure and in fast-paced environments

* **Problem-Solving:** Mechanical aptitude with basic troubleshooting capabilities

* **Organization:** Highly detail-oriented and well-organized in managing tasks and data

* **Languages:** Bilingual in English and French

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.wearepioneer.com}{Pioneer Commercial Cleaning}}\end{flushleft}
    \begin{flushright}June 2025 - Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Technolgy Consultant}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Designed and implemented a unified Snowflake data warehouse that consolidated data from WinTeam, Paycom, and Cora databases, eliminating silos and enabling company-wide reporting on workforce, payroll, and operations.
* Built automated ETL pipelines with Python, GitLab CI/CD, and Snowflake to streamline ingestion from MySQL and SFTP into Snowflake via AWS S3 and pipelines, reducing manual effort and enabling near real-time data availability.
* Developed interactive dashboards in Metabase that provided company leadership with actionable insights on workforce, payroll, and operational KPIs, driving more data-informed strategic and financial decisions.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.hollywoodcasinocharlestown.com}{Charls Town Casino}}\end{flushleft}
    \begin{flushright}May 2025 - Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Revenue Audit Clerk}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Perform detailed audits by interpreting technical documents, applying business math, and following written, oral, and diagram-based procedures to ensure compliance and accuracy.
* Utilize Microsoft Excel, Access, and Word at an advanced level to create reports, analyze data, and manage audit records efficiently.
* Collect, verify, and analyze financial and operational data to identify discrepancies, write audit findings, and support regulatory compliance.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://marcusharrisfoundation.org/}{Marcus Harris Foundation}}\end{flushleft}
    \begin{flushright}December 2024 - April 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Analyst}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Spearheaded the collection and processing of large-scale nonprofit data from the IRS tax-exempt organization database using Python (Pandas), delivering clean, analysis-ready datasets for internal use.
* Consolidated and standardized disparate data sources to improve reporting reliability and enable comprehensive cross-source analysis.
* Analyzed marketing and outreach performance trends, delivering actionable insights through Python dashboards and Excel summaries that shaped data-driven engagement and fundraising strategies.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/orgs/BYUIDSconsulting/teams/ai-ta-bot/repositories}{Brigham Young University - Idaho}}\end{flushleft}
    \begin{flushright}January 2025 - April 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Analyst}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Led financial forecasting efforts and cost-benefit analyses for AI tutor implementation using Python (Pandas, NumPy), comparing multiple AI model configurations to identify the most cost-effective deployment strategy.
* Evaluated implementation scenarios by analyzing trade-offs between AI-assisted tutoring and traditional TA support, providing data-driven recommendations that optimized operational efficiency and budget allocation.
* Presented findings and insights using Power BI dashboards and visual reports, improving stakeholder understanding and guiding budget and educational technology decisions.
\vspace{7pt}

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.1800contacts.com}{1800 Contacts}}\end{flushleft}
    \begin{flushright}April 2023 - Decmember 2023\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Chat Support Specailist}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Actively promoted lens upgrades and complementary products during chat interactions, helping boost order value and enhance the customer experience.
* Responded to a high volume of live customer chats daily, delivering accurate, friendly, and professional support while navigating multiple systems simultaneously to resolve complex inquiries efficiently.
* Reviewed and processed eyewear orders by interpreting prescription details and customer preferences, ensuring proper lens type, frame selection, and shipping accuracy for customer satisfaction.
* Utilized Microsoft Office applications and proprietary tools to maintain meticulous records of customer interactions, helping streamline order fulfillment and future support.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.melaleuca.com}{Melaleuca}}\end{flushleft}
    \begin{flushright}April 2022 - April 2023\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{French Customer Service Support}\end{flushleft}
    \begin{flushright}\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Promoted product benefits and membership upgrades during customer support interactions, contributing to increased sales.
* Provided high-quality bilingual support via phone and email to French-speaking customers, addressing questions on wellness products, membership benefits, and account discrepancies with clarity and professionalism.
* Explained complex product information, including health benefits, ingredients, and usage instructions, to international customers in both French and English, ensuring full customer understanding and compliance.
* Assisted with billing inquiries, refunds, and adjustments by thoroughly reviewing account activity, documenting changes, ensuring resolution in accordance with company policies and procedures.

\vspace{7pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf SELECTED PROJECTS}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://huggingface.co/spaces/scotty369/Townsend_streamlit-dockerWI25}{Streamlit C-Store App}}\end{flushleft}
    \begin{flushright}April 2025 – June 2025\end{flushright}
  \end{multicols}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Engineering | Streamlit, HuggingFace}\end{flushleft}
    \begin{flushright}\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Deployed an end-to-end analytics application by containerizing a Streamlit dashboard with Docker and hosting it on Hugging Face Spaces, making insights accessible to non-technical users.
* Transformed transactional and product-level data into interactive KPIs, charts, tables, and filters, enabling on-demand answers to product and category-level business questions.
* Integrated Databricks pipelines with the Streamlit app to ensure fresh data availability, reducing reporting lag and supporting faster, data-driven decision-making.
\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/scotty369}{Convenience Store Data Engineering}}\end{flushleft}
    \begin{flushright}January 2025 – April 2025\end{flushright}
  \end{multicols}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Engineering | Databricks, PySpark, Plotly}\end{flushleft}
    \begin{flushright}\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Built scalable ETL pipelines in Databricks to clean, transform, and integrate millions of retail transactions and product records from U.S. convenience stores.
* Engineered meaningful PySpark features to enhance downstream analytics and enrich business reporting with new insights into sales and margin performance.
* Performed exploratory analysis and developed visual dashboards with Plotly and Seaborn to uncover key retail trends, shopper behavior patterns, and category-level performance drivers.

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://github.com/scotty369}{Student Performance ML Analysis}}\end{flushleft}
    \begin{flushright}October 2024 – December 2024\end{flushright}
  \end{multicols}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Machine Learning | Colab, Random Forest, Seaborn}\end{flushleft}
    \begin{flushright}\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Built and tuned Linear Regression and Random Forest models to predict academic performance using cross-validation and
GridSearchCV
* Engineered features (e.g., average_score) and applied preprocessing techniques (one-hot encoding, standardization) to im-
prove model accuracy.
* Interpreted results with visual tools like residual plots and feature importance charts, translating findings into actionable
insights.